// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faonvjhsrxdehvpiatuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhb252amhzcnhkZWh2cGlhdHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTIxMTgsImV4cCI6MjA3MjI2ODExOH0.n7wYFz7H1_uekI9t48zK9YiAA9vE6n0GB2R74lgcGLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});